language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
  - echo "====================="
  - echo $MYSECRET 
  - cargo build --verbose --all
  - cargo test --verbose --all
