# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

# based on https://nbsoftsolutions.com/blog/azure-pipelines-for-rust-projects
steps:
  - script: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: Install rust
  - script: cargo build --all
    displayName: Cargo build
  - script: cargo test --all
    displayName: Cargo test
  - script: |
    echo "================"
    echo $env:MY_SECRET_VAR
  env:
    MY_SECRET_VAR: $(MYSECRET)


